// pgperffarm-front-end/src/components/Login.vue
<template>
    <v-app>
    <main>
      <v-content>
        <pg-toolbar></pg-toolbar>
        <pg-navbar></pg-navbar>

            <v-container>
            <v-layout>
              <v-flex>
                <v-card flat class="login-v-card-upper">
                    <img src="../assets/images/full-logo.png" height="10%" width="10%" align-center>
                  <v-toolbar flat class="login-v-card-upper-toolbar">
                    <v-toolbar-title class="login-v-card-upper-toolbar-title">Log in to manage your machines!</v-toolbar-title>
                  </v-toolbar>
              </v-card>
              <v-card flat class="login-v-card">
                  <v-card-text>
                    <v-form>
                      <v-text-field prepend-icon="person" name="username" v-model="input.username" label="Username" type="text"></v-text-field>
                      <v-text-field prepend-icon="lock" name="password" v-model="input.password" label="Password" id="password" type="password"></v-text-field>
                    </v-form>
                  </v-card-text>
                  <v-card-actions>
                    <v-spacer></v-spacer>
                    <v-btn v-on:click="login()">Login</v-btn>
                  </v-card-actions>
                </v-card>
              </v-flex>
            </v-layout>
          </v-container>

        <pg-footer></pg-footer>
      </v-content>
    </main>
  </v-app>
</template>

<script>
    import PgNavbar from './Navbar.vue'
    import PgFooter from './Footer.vue'
    import PgToolbar from './Toolbar.vue'

    import PGUtil from '../util/util.jsx'
    import PGConstant from '../util/constant.jsx'
    import User from '../service/user-service.js'

    const util = new PGUtil();
    const user = new User();

    export default {
        name: 'Login',
        components: {
            PgNavbar,
            PgFooter,
            PgToolbar
        },
        data() {
            return {
                input: {
                    username: "",
                    password: ""
                }
            }
        },

        methods: {
            login() {

                let username = this.input.username
                let password = this.input.password

                if(username != "" && password != "") {

                    let loginInfo = {username, password}
                    
                    user.login(loginInfo).then((res) => {

                        util.setStorage('userInfo', res);
                        window.alert('Login succeeded!');
                        window.location.href = this.state.redirect;

                    }, (err) => {

                        if (PGConstant.AuthorizedErrorCode === err) {
                            util.errorTips('Wrong username or password!');
                        }
                        else {
                            // ReferenceError: $ is not defined
                            window.alert(err);
                        }

                    });

                // this.$emit("authenticated", true);
                // this.$router.replace({ name: "secure" });
                // this.$store.dispatch('login', { email, password })
                // .then(() => this.$router.push('/'))
                // .catch(err => console.log(err))

            }

                else {
                    window.alert('Empty username or password!');
                }
            }
        }
    }
</script>

// front-end/src/page/login/index.jsx
import React from 'react';
// import './index.css';
import PGUtil    from 'util/util.jsx'
import PGConstant from 'util/constant.jsx'
const _util = new PGUtil();
import User         from 'service/user-service.jsx'
const _user = new User();

class Login extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            username: '',
            password: '',
            redirect: _util.getUrlParam('redirect') || 'portal',
        }
    }

    componentWillMount() {
        document.title = 'LOGIN';
        let userinfo = _util.getStorage('userInfo')|| {};
        if(userinfo.token){
            this.props.history.push('/portal')
            // window.location.href = '/portal';
        }

    }

    onInputChange(e) {
        let inputValue = e.target.value,
            inputName = e.target.name;
        this.setState({
            [inputName]: inputValue
        });
    }

    onInputKeyUp(e) {
        if (e.keyCode === 13) {
            this.onSubmit();
        }
    }

    onSubmit() {
        let loginInfo = {
                username: this.state.username,
                password: this.state.password
            },
            checkResult = _user.checkLoginInfo(loginInfo);
        // check success
        if (checkResult.status) {
            _user.login(loginInfo).then((res) => {
                // console.dir(res)
                _util.setStorage('userInfo', res);
                // this.props.history.push(this.state.redirect);
                window.location.href = this.state.redirect;
            }, (err) => {
                // console.log(err)
                if (PGConstant.AuthorizedErrorCode === err) {
                    _util.errorTips('username or password is mistake!');
                }else{
                    _util.errorTips('login fail');
                }
            });
        }
        // check failure
        else {

            _util.errorTips(checkResult.msg);
        }

    }

    render() {
        return (
            <div id="page-wrapper">
                <div className="row">
                    <div className="col-lg-16">
                        <div className="panel panel-default">
                            <div className="panel-heading">
                                login to manage your machines!
                            </div>
                            <div className="panel-body">
                                <div className="row">
                                    {/*<!-- /.col-lg-6 (nested) -->*/}
                                    <div className="col-lg-12">
                                        <h4>Login Form</h4>
                                        <form role="form">
                                            <div className="form-group">
                                                {/*<label className="control-label" for="inputLogin"> login input</label>*/}
                                                <input type="text" className="form-control" id="inputLogin"
                                                       placeholder="Username or email"
                                                       name="username"
                                                       onKeyUp={e => this.onInputKeyUp(e)}
                                                       onChange={e => this.onInputChange(e)}/>
                                            </div>
                                            <div className="form-group">
                                                <input type="text" className="form-control" id="inputPwd"
                                                       name="password"
                                                       placeholder="password" onKeyUp={e => this.onInputKeyUp(e)}
                                                       onChange={e => this.onInputChange(e)}/>
                                            </div>
                                            <button type="button" className="btn btn-primary"  onClick={e => {this.onSubmit(e)}}>Button</button>
                                        </form>
                                    </div>
                                    {/*<!-- /.col-lg-6 (nested) -->*/}
                                </div>
                                {/*<!-- /.row (nested) -->*/}
                            </div>
                            {/*<!-- /.panel-body -->*/}
                        </div>
                        {/*<!-- /.panel -->*/}
                    </div>
                    {/*<!-- /.col-lg-12 -->*/}
                </div>
            </div>
        )
    }
}

export default Login;
